//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DressBookingDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dress()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int SizeId { get; set; }
        public decimal PriceToBuy { get; set; }
        public decimal PriceToBook { get; set; }
        public bool IsBought { get; set; }
        public bool IsCopy { get; set; }
        public bool Wedding { get; set; }
        public string FrontPicLink { get; set; }
        public string CloserPicLink { get; set; }
        public string BackPicLink { get; set; }
    
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
